---
title: "Quidel dashboard"
author: "Delphi Lab"
date: "`r format(Sys.time(), '%B %d, %Y - %H:%M:%S')`"
output:
  html_document:
    code_folding: hide
params:
  source: "quidel"
  signal: "covid_ag_raw_pct_positive"
---

```{r, include = FALSE}
source("dashboard_functions.R")
```

### Coverage {.tabset}

#### States
```{r, include = FALSE}
df_states = covidcast_signal(params$source,
                             params$signal,
                             start_day = twenty_eight_days_ago,
                             geo_type = "state")
```

```{r, fig.width = 10, fig.height = 5}
plot_unique_geo_types_present(df_states, "states")
```

```{r, fig.width = 10, fig.height = 8}
plot_data_frequency_choro(df_states, "state")
```

#### Metro Areas

```{r, include = FALSE}
df_metros = covidcast_signal(params$source,
                             params$signal,
                             start_day = twenty_eight_days_ago,
                             geo_type = "msa")
```

```{r, fig.width = 10, fig.height = 5}
plot_unique_geo_types_present(df_metros, "metros")
```

#### Samples
Not available for this signal.
