---
title: "USA facts dashboard"
author: "Delphi Lab"
date: "`r format(Sys.time(), '%B %d, %Y - %H:%M:%S')`"
output:
  html_document:
    code_folding: hide
params:
  source: "usa-facts"
  signal: "confirmed_cumulative_num"
---

```{r, include = FALSE}
source("dashboard_functions.R")
```

### Coverage {.tabset}
#### County
```{r, include = FALSE}
df_counties = covidcast_signal(params$source,
                               params$signal,
                               start_day = twenty_eight_days_ago,
                               geo_type = "county")
```

```{r, fig.width = 10, fig.height = 5}
plot_28_day_unique(df_counties, "counties")
```

```{r, fig.width = 10, fig.height = 8}
plot_28_day_frequency_county(df_counties)
```

#### Metro Areas

```{r, include = FALSE}
df_metros = covidcast_signal(params$source,
                             params$signal,
                             start_day = twenty_eight_days_ago,
                             geo_type = "msa")
```

```{r, fig.width = 10, fig.height = 5}
plot_28_day_unique(df_metros, "metros")
```

#### Sample Size

```{r, fig.width = 10, fig.height = 5}
df_states = covidcast_signal(params$source,
                             params$signal,
                             start_day = twenty_eight_days_ago,
                             geo_type = "state")

plot_28_day_sample_volume(df_states, "Raw confirmed volume")
```
