---
title: "Plotting demo with `covidcast` R package"
author: "Delphi Group"
date: "July 12, 2020"
---

```{r, include=FALSE}
knitr::opts_chunk$set(fig.width=10, fig.height=8)
```

Fetching data 
===

```{r}
library(covidcast)

# Get data from the API (see https://cmu-delphi.github.io/delphi-epidata/api/covidcast.html 
# for detailed docuemtation)
df_comb = covidcast_signal(data_source = "indicator-combination",  
                           signal = "nmf_day_doc_fbc_fbs_ght", 
                           start_day = "20200704")
summary(df_comb)
```

Choropleth maps
===

```{r}
# Plot a choropleth map: colors are approximately the same as at covidcast.cmu.edu)
plot(df_comb)

# Plot a choropleth map for direction: decreasing and increasing colors are roughly the
# same as at covidcast.cmu.edu, but steady color has been changed to yellow-gray, so as
# to avoid confusion with the use of gray for missing
plot(df_comb, direction = TRUE)

# Example with customized options: show data on a different day, use cyan-magenta colors, 
# a slightly greater degree of transparency (for mega counties), and set custom title
plot(df_comb, time_value = "2020-07-04", choro_col = cm.colors(10), alpha = 0.4, 
     title = "Combination of COVID-19 Indicators on 2020-06-04")

# One more example: only show Pennsylvania and New York states
plot(df_comb, include = c("PA", "NY"))

# One more example: custom (log-spaced) color scale for incident case numbers
suppressMessages({
df_inum = covidcast_signal(data_source = "jhu-csse", 
                           signal = "confirmed_7dav_incidence_num",
                           start_day = "20200704")
})

breaks = c(0, 1, 2, 5, 10, 20, 50, 100, 200) 
colors = c("#D3D3D3", "#FFFFCC", "#FEDDA2", "#FDBB79", "#FD9950", "#EB7538", "#C74E32",
           "#A3272C", "#800026")

# Note that length(breaks) == length(colors) by design. This is interpreted so that we
# we assign colors[i] iff the value satisfies: breaks[i] <= value < breaks[i+1], where
# we take breaks[N] = Inf, for N = length(breaks)

plot(df_inum, choro_col = colors, choro_params = list(breaks = breaks),
     title = paste("New COVID Cases (7 Day Trailing Average) on", max(df_inum$time_value)))

# One more example: which counties have cumulative case rates of at least 1/100?
suppressMessages({
df_cprop = covidcast_signal(data_source = "jhu-csse",
                            signal = "confirmed_cumulative_prop",
                            start_day = "20200704")
})

breaks = c(0, 1000)
colors = c("#D3D3D3", "#FFC0CB")

plot(df_cprop, choro_col = colors, choro_params = list(breaks = breaks, legend_width = 5), 
     title = paste("Cumulative COVID Cases per 100k People on", max(df_cprop$time_value)))
```

Bubble maps
===

```{r}
# Plot a bubble map: default is 8 bins evenly-spaced over the auto range (with the zero
# bin assigned a zero bubble size). For the legend labels, we interpret it as follows: 
# each bubble size means *at least* the corresponding value
plot(df_inum, plot_type = "bubble")

# Example with customized options: show Texas, red bubbles, bigger sizes, custom breaks.
# Then plot the same but for incidence proportion 
suppressMessages({
df_iprop = covidcast_signal(data_source = "jhu-csse", 
                            signal = "confirmed_7dav_incidence_prop",
                            start_day = "20200704")
})
breaks1 = c(0, 1, 10, 100, 1000)
breaks2 = c(0, 10, 50, 100, 500)
p1 = plot(df_inum, plot_type = "bubble", bubble_params = list(breaks = breaks1, max_size = 6), 
          include = "TX", bubble_col = "red", title = paste("Incidence Number on", 
                                                            max(df_inum$time_value)))
p2 = plot(df_iprop, plot_type = "bubble", bubble_params = list(breaks = breaks2, max_size = 6), 
          include = "TX", bubble_col = "red", title = paste("Incidence Proportion on", 
                                                            max(df_iprop$time_value)))
gridExtra::grid.arrange(p1, p2, nrow = 1)

# One more example: bubble plot for combined indicator (doesn't really "work" that well)
plot(df_comb, plot_type = "bubble")
```

State examples
===

```{r}
suppressMessages({
df_comb_st = covidcast_signal(data_source = "indicator-combination",  
                              signal = "nmf_day_doc_fbc_fbs_ght", 
                              geo_type = "state")
df_inum_st = covidcast_signal(data_source = "jhu-csse", 
                              signal = "confirmed_7dav_incidence_num",
                              geo_type = "state")
})

plot(df_comb_st)
plot(df_inum_st, plot_type = "bubble")
```

```{r, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=6)
```

Time series plots
===

```{r}
# Plot a time series graph: default is to show the last 2 weeks
plot(df_comb_st, plot_type = "line", geo_values = c("ca","pa","tx","ny"))
plot(df_inum_st, plot_type = "line", geo_values = c("ca","pa","tx","ny"))

# Example with customized options: set the num_days argument to Inf, effectively plotting
# back until data was first available
plot(df_comb_st, plot_type = "line", geo_values = c("ca","pa","tx","ny"),
     line_params = list(num_days = Inf))
plot(df_inum_st, plot_type = "line", geo_values = c("ca","pa","tx","ny"),
     line_params = list(num_days = Inf))
```
