---
title: 1. Estimate derivatives of signals 
description: Estimate derivatives and related statistics of signals.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{1. Estimate derivatives of signals}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
knitr::opts_chunk$set(cache = TRUE, autodep = TRUE, cache.comments = TRUE)
```

## Estimating derivatives of signals

TODO, blah load data

```{r}
library(covidcast)

start_day <- "2020-06-01"
end_day <- "2020-11-15"

case_rates <- suppressMessages(
  covidcast_signal(data_source = "usa-facts", 
                   signal = "confirmed_7dav_incidence_prop",
                   start_day = start_day, end_day = end_day, 
                   geo_type = "state"))

summary(case_rates)
```

TODO, blah try linear regression

```{r}
library(modeltools)
library(dplyr)

case_rates <- estimate_deriv(case_rates, method = "linear-reg", n = 14)

case_rates %>% 
  arrange(geo_value) %>% 
  filter(time_value <= "2020-06-14") %>%
  select(geo_value, time_value, value, deriv) 
```

TODO, blah plot it

```{r, fig.width = 8, fig.height = 4}
library(ggplot2)
library(gridExtra)

case_rates_fl = case_rates %>% filter(geo_value == "fl")
threshold = 0.25

p1 = ggplot(case_rates_fl, aes(x = time_value, y = value)) +
  geom_line(color = "black") + 
  geom_point(data = case_rates_fl %>% filter(deriv >= threshold),
             aes(x = time_value, y = value), color = "blue") + 
  labs(x = "Date", y = "Cases per 100,00 people") 
p2 = ggplot(case_rates_fl, aes(x = time_value, y = deriv)) +
  geom_line(color = "red") + 
  labs(x = "Date", y = "Derivative (linear regression)") +
  geom_hline(yintercept = threshold, color = "blue", linetype = 2)
grid.arrange(p1, p2, nrow = 1)
```

TODO, blah try smoothing splines two ways, plot them

```{r, fig.width = 8, fig.height = 4}
case_rates <- estimate_deriv(case_rates, method = "smooth-spline", n = 28,
                             new_col = "deriv_ss_df", params = list(df = 8))

case_rates <- estimate_deriv(case_rates, method = "smooth-spline", n = 28,
                             new_col = "deriv_ss_cv", params = list(cv = TRUE))

case_rates %>% 
  arrange(geo_value) %>% 
  filter(time_value <= "2020-06-14") %>%
  select(geo_value, time_value, value, deriv, deriv_ss_df, deriv_ss_cv) 

case_rates_fl = case_rates %>% filter(geo_value == "fl")
threshold = 0.25

p1 = ggplot(case_rates_fl, aes(x = time_value, y = value)) +
  geom_line(color = "black") + 
  geom_point(data = case_rates_fl %>% filter(deriv_ss_df >= threshold),
             aes(x = time_value, y = value), color = "purple") + 
  labs(x = "Date", y = "Cases per 100,00 people") 
p2 = ggplot(case_rates_fl, aes(x = time_value, y = deriv_ss_df)) +
  geom_line(color = "red") + 
  labs(x = "Date", y = "Derivative (smoothing spline, CV-tuned)") +
  geom_hline(yintercept = threshold, color = "purple", linetype = 2)
grid.arrange(p1, p2, nrow = 1)

p1 = ggplot(case_rates_fl, aes(x = time_value, y = value)) +
  geom_line(color = "black") + 
  geom_point(data = case_rates_fl %>% filter(deriv_ss_cv >= threshold),
             aes(x = time_value, y = value), color = "green") + 
  labs(x = "Date", y = "Cases per 100,00 people") 
p2 = ggplot(case_rates_fl, aes(x = time_value, y = deriv_ss_cv)) +
  geom_line(color = "red") + 
  labs(x = "Date", y = "Derivative (smoothing spline, df = 10)") +
  geom_hline(yintercept = threshold, color = "green", linetype = 2)
grid.arrange(p1, p2, nrow = 1)
```