test_that("we can validate geo types", {
  pct <- tibble(type_len = 2L, has_chars = TRUE)
  expect_error(validate_geo_type("xyz", pct))
  expect_equal(validate_geo_type("state", pct), "state")
  expect_equal(validate_geo_type("county", pct), "state")
  expect_error(validate_geo_type("hrr", pct))
  pct <- tibble(type_len = 1:2, has_chars = FALSE)
  expect_equal(validate_geo_type("hrr",pct), "hrr")
  expect_equal(validate_geo_type("msa",pct), "msa")
  expect_equal(validate_geo_type("dma",pct), "dma")
  expect_error(validate_geo_type("state",pct))
  expect_error(validate_geo_type("county",pct))
  pct <- tibble(type_len = 5L, has_chars = FALSE)
  expect_equal(validate_geo_type("county", pct), "county")
  expect_equal(validate_geo_type("state", pct), "county")
  expect_equal(validate_geo_type("hrr", pct), "hrr")
  pct <- tibble(type_len = 1L, has_chars = TRUE)
  expect_error(validate_geo_type("state",pct))
  expect_error(validate_geo_type("county",pct))
  pct <- tibble(type_len = 1L, has_chars = FALSE)
  expect_error(validate_geo_type("state",pct))
  expect_error(validate_geo_type("county",pct))
})
