# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Lint and Testing

on:
  push:
    branches: [ main, r-pkg-devel ]
  pull_request:
    branches: [ main, r-pkg-devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Python-packages/covidcast-py/
    strategy:
      matrix:
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_ci.txt
    - name: Lint with pylint and mypy
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
