name: python_lint_and_test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Python-packages/covidcast-py/requirements.txt
    - name: Lint with pylint
      run: |
        pylint Python-packages/covidcast-py/covidcast/
    - name: Test with pytest
      run: |
        pytest Python-packages/covidcast-py/

