# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R_covidcast

on:
  push:
    branches: [ main, r-pkg-devel ]
  pull_request:
    branches: [ main, r-pkg-devel ]

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: R-packages/covidcast/
    strategy:
      matrix:
        r-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install linux dependencies  
        run: |
            sudo apt-get install libcurl4-openssl-dev
            sudo apt-get install libudunits2-dev
            sudo apt-get install libgdal-dev
            sudo apt-get install libgit2-dev
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-2-
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--ignore-vignettes", "--as-cran"), build_args = c("--no-build-vignettes"), error_on = "error")
        shell: Rscript {0}
